rnv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^', include('page.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/forms.py
from django import forms

class MultiForm(forms.Form):
    name = forms.CharField(required=False, max_length=50)
    tel = forms.CharField(required=True, max_length=15)
    mail = forms.EmailField(required=False)
    service = forms.CharField(required=False, max_length=50)
    message = forms.CharField(required=False, max_length=360, widget=forms.Textarea)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="  ">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
		<link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300,300italic,400italic,700italic&amp;subset=latin,cyrillic,cyrillic-ext" rel="stylesheet" type="text/css">
		<title>{%block title%}Работы на высоте{%endblock title%}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="{%block description%}{%endblock description%}" />
    <meta name="keywords" content="{%block keywords%}{%endblock keywords%}">
		<link href='{% static '/css/style.css' %}' rel='stylesheet' type='text/css'>
		<link href='{% static '/css/popup.css' %}' rel='stylesheet' type='text/css'>
		{% block extracss %}{%endblock extracss%}
		<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
		<link rel="canonical" href="{% block canonical %}{% endblock canonical %}"/>
	</head>
	<body>
		<div id="panel"></div>
		<div class="body">
			<div class="body_media"></div>

			<header class="topmenu-SECOND">
							<div class="container maxwidth-theme">
								<div class="top-row row visible-xs">
									<div class="col-md-12 col-sm-12 col-xs-12">
										<div class="info-text">
											<div class="phone">
												<i class="icon icon-phone"></i>
												+7 (921) 964-69-11								</div>
											<div class="skype hidden-xs">
												<i class="icon icon-skype"></i>
												your.skype.ru								</div>
											<div class="email">
												<i class="icon icon-envelope"></i>
												<a href="mailto:mypromalp@gmail.com">mypromalp@gmail.com</a>								</div>
										</div>
									</div>
								</div>
								<div class="logo-row row">
																<div class="col-md-4 col-sm-4">
											<div class="logo">
												<a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>								</div>
										</div>
										<div class="col-md-3 col-sm-3 hidden-xs">
											<div class="top-description">
											    {% if messages %}
                                                {% for message in messages %}
                                                <p id="p-hide" style="margin-bottom: 10px;margin-top: -27px;">{{ message }} <span id="hide" style="cursor:  pointer;font-size: 20px;font-weight:  bold;">x</span></p>
                                                {% endfor %}
                                                {% endif %}
												<p style="text-align: center;">Промышленный альпинизм<br>
			в Санкт-Петербурге</p>								</div>
										</div>
										<div class="col-md-5 col-sm-5 col-xs-12">
											<div class="top-callback hidden-xs">
												<div class="callback pull-right" data-event="jqm" data-param-id="26" data-name="callback">
													<i class="icon icon-phone"></i>
													<div>
														<span>Заказать звонок</span>
													</div>
												</div>
												<div class="phone pull-right hidden-xs">
													+7 (921) 964-69-11									</div>
											</div>
											<button class="btn btn-responsive-nav visible-xs" data-toggle="collapse" data-target=".nav-main-collapse">
												<i class="icon icon-bars"></i>
											</button>
										</div>
										</div>







{% block content %}{% endblock content %}

	</div>
{# callbackFoem #}
<noindex>
	<div class="callback_frame jqmWindow jqm-init" style="width: 400px; z-index: 3000; opacity: 1; display: none;">
		<span class="jqmClose top-close icon icon-times"></span>
		<div>
			<div class="form popup">
				<form action="" method="POST" id="callback">
					{% csrf_token %}
					<div class="form-header">
						<i class="icon icon-phone"></i>
						<div class="text">
							<div class="title">Обратный звонок</div>Представьтесь, мы вам перезвоним.</div>
						</div>
						<div class="form-body">
							<div class="row" data-sid="FIO">
								<div class="form-group">
									<div class="col-md-12">
										<label for="FIO">Имя:</label>
										<div class="input">
											<input type="text" name="name" id="id_name" maxlength="50" class="form-control"><i class="icon icon-user"></i>
										</div>
									</div>
								</div>
							</div>
							<div class="row" data-sid="PHONE">
								<div class="form-group">
									<div class="col-md-12">
										<label for="PHONE">Телефон: <span class="required-star">*</span></label>
										<div class="input">
											<input type="text" name="tel" required id="id_tel" maxlength="15" class="form-control required phone"><i class="icon icon-phone"></i>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="form-footer clearfix">
							<div class="pull-left required-fileds">
								<i class="star">*</i> - Обязательные поля
							</div>
							<div class="pull-right">
								<button class="btn btn-default" type="submit">Отправить</button><br>
								<input type="hidden" name="form_submit" value="Отправить">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
</noindex>
{# End callbackForm #}

		<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
		<script src="{% static 'js/jquery.maskedinput.js' %}"></script>
		<script src="{% static 'js/page.js' %}"></script>

		<script type="text/javascript">
		$(document).ready(function() {
		  $('.callback').on('click', function(){
		    $('body').append('<div class="jqmOverlay" style="height: 100%; width: 100%; position: fixed; left: 0px; top: 0px; z-index: 2999; opacity: 0.5;"></div>');
		    $('.callback_frame').addClass('show');
		  });

		  $('.jqmClose').on('click', function() {
		    /* Скрыть окно, когда кликаем вне его области */
		    $('.callback_frame').removeClass('show');
		    $('.jqmOverlay').hide();
		  });

		  var boxWidth = 400;

		  function centerBox() {
		    var winWidth = $(window).width();
		    var winHeight = $(document).height();
		    var scrollPos = $(window).scrollTop();

		    var disWidth = (winWidth - boxWidth) / 2
		    var disHeight = scrollPos + 50;

		    $('.callback_frame').css({'width' : boxWidth+'px', 'left' : disWidth+'px', 'top' : disHeight+'px'});
		    $('.jqmOverlay').css({'width' : winWidth+'px', 'height' : winHeight+'px'});

		    return false;
		  };
		  $(window).resize(centerBox);
		  $(window).scroll(centerBox);
		  centerBox();
		});
		</script>
		<script type="text/javascript">
		$(function(){
		  $(".phone").mask("8(999) 999-9999");
		});
		</script>
		<script>
		    $("#hide").click(function(){
                $("#p-hide").hide();
            });
		</script>
    {% block extrajs %}{% endblock extrajs %}
	</body>
</html>

templates/main.html
{% extends "base.html" %}
{% load staticfiles %}
{% load mptt_tags %}
{% block title %}{{main_page.title}}{% endblock title %}
{%block description%}{{main_page.description}}{%endblock description%}
{%block keywords%}{{main_page.keywords}}{%endblock keywords%}
{% block canonical %}{{ request.build_absolute_uri }}{% endblock canonical %}

{%block content%}

<div class="menu-row row">
  <div class="col-md-12">
    <div class="nav-main-collapse collapse">
      <div class="menu-and-search">
        <nav class="mega-menu ">
          <div class="table-menu hidden-xs">
            <table>
              <tr>
                {% recursetree main_menu %}
                {% if node.visible_in_menu %}
									{% if node.menu_name == 'Главная' %}
                    <td {% if '/' == request.path  %}class="active"{% endif %}>
                      <div class="wrap"><a href="/" title="{{node.menu_name}}">{{node.menu_name}}</a></div>
                    </td>
  								{% else %}
		  					    {% if node.get_descendants %}
		  					    <td class="dropdown{% if node.get_absolute_url == request.path %} active{% endif %}">
											<div class="wrap">
												<a class="dropdown-toggle" href="{{node.get_absolute_url}}" title="{{ node.menu_name }}">{{ node.menu_name }} <i class="icon icon-angle-down"></i></a>
												<ul class="dropdown-menu">
													{% for child in node.get_descendants %}
														{% if child.visible_in_menu %}
															{% if child.level == 1 %}
																{% if child.get_descendants %}
																<li class="dropdown-submenu">
																	<a href="{{child.get_absolute_url}}" title="{{ child.menu_name }}">{{ child.menu_name }}</a>
																	<ul class="dropdown-menu">
																		{% for children in child.get_descendants %}
																			{% if children.visible_in_menu %}
																			<li><a href="{{children.get_absolute_url}}">{{ children.menu_name }}</a></li>
																			{% endif %}
																		{% endfor %}
																	</ul>
																</li>
																{% else %}
																<li><a href="{{child.get_absolute_url}}" title="{{ child.menu_name }}">{{ child.menu_name }}</a></li>
																{% endif %}
															{% endif %}
														{% endif %}
													{% endfor %}
												</ul>
											</div>
										</td>
										{% else %}
										<td {% if node.get_absolute_url == request.path %}class="active"{% endif %}>
											<div class="wrap">
												<a class="" href="{{node.get_absolute_url}}" title="{{node.menu_name}}">{{node.menu_name}}</a>
											</div>
										</td>
										{% endif %}
									{% endif %}
  						{% endif %}
              {% endrecursetree %}
						</tr>
            </table>
          </div>
          <ul class="nav nav-pills responsive-menu visible-xs" id="mainMenu">
          {% recursetree main_menu %}
					{% if node.visible_in_menu %}
						{% if node.get_descendants %}
						<li class="dropdown">
							<a class="dropdown-toggle" href="{{node.get_absolute_url}}" title="{{ node.menu_name }}">{{ node.menu_name }}<i class="icon icon-angle-down"></i></a>
	            <ul class="dropdown-menu">
								{% for child in node.get_descendants %}
								{% if child.level == 1 %}
									{% if child.get_descendants %}
									<li class="dropdown-submenu dropdown-toggle">
										<a class="dropdown-toggle" href="{{ child.get_absolute_url }}" title="{{ child.menu_name }}">{{ child.menu_name }}<i class="icon icon-angle-down"></i></a>
										<ul class="dropdown-menu">
											{% for ch in child.get_descendants %}
											<li class=" "><a href="{{ ch.get_absolute_url }}" title="{{ ch.menu_name }}">{{ ch.menu_name }}</a></li>
											{% endfor %}
										</ul>
									</li>
									{% else %}
									<li class=" "><a href="{{ child.get_absolute_url }}" title="{{ child.menu_name }}">{{ child.menu_name }}</a></li>
									{% endif %}
								{% endif %}
								{% endfor %}
	            </ul>
	          </li>
						{% else %}
							{% if node.menu_name == 'Главная' %}
							<li class="active">
								<a class="" href="/" title="{{ node.menu_name }}">{{ node.menu_name }}</a>
							</li>
							{% else %}
							<li class=" ">
								<a class="" href="{{node.get_absolute_url}}" title="{{ node.menu_name }}">{{ node.menu_name }}</a>
							</li>
							{% endif %}
						{% endif %}
					{% endif %}
          {% endrecursetree %}
					</ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <div class="line-row visible-xs"></div>

<div class="banners">
  <div class="first">
    <div class="col-md-12 col-sm-12 big" >
      <div class="flexslider unstyled row" data-plugin-options='{"animation": "slide", "directionNav": true, "controlNav" :true, "animationLoop": true, "slideshow": true, "slideshowSpeed": 5000, "animationSpeed": 600, "counts": [1, 1, 1]}'>
        <ul class="slides items">
          {% for slide in main_slider %}
          <li class="col-md-12 col-sm-12 item">
            <a href="{% if slide.url %}{{slide.url}}{% endif %}">
              <div class="image" style="background:url('{{slide.image.url}}') center center / 750px 399px no-repeat scroll transparent;" data-background='{"width": 750, "height": 399}'></div>
              <div class="info">
                <div>
                  <h3>{{slide.title}}</h3>
                  <p>{{slide.text}}</p>
                </div>
              </div>
            </a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="about row">
<div class="col-md-12 col-sm-12">
    <noindex>
<h2 class="underline">{% if main_page.header_h1 %}{{main_page.header_h1}}{% else %}{{main_page.menu_name}}{% endif %}</h2>
{% autoescape off %}{{main_page.content_up}}{% endautoescape %}
    </noindex>
</div>
</div>
</div>
</header>
<div role="main" class="main">
  <div class="container maxwidth-theme">
    <div class="row">
      <div class="col-md-12">
        <div class="news front">
          <h3 class="underline">Новости</h3>
          <a href="/kompaniya/novosti/" class="btn btn-default btn-xs wc"><i class="icon icon-angle-right"></i><span>Все новости</span></a>
          <div class="row items">
            {% for news in news_list %}
            <div class="item col-md-4 col-sm-6">
              {% if news.image %}
              <div class="image">
                <a href="{{news.get_absolute_url}}">
                  <img class="img-responsive" src="{{news.image.url}}" alt="{{news.header_h1}}" title="{{news.title}}" />
                </a>
              </div>
              {% endif %}
              <div class="info">
                <div class="date">{{news.date}}</div>
                <a href="{{news.get_absolute_url}}">
                  <div class="title">{{news.header_h1}}</div>
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="prefooter">
    <div class="container maxwidth-theme">
      <div class="front item-views table projects front-projects">
        <h3 class="underline">Выполненные проекты</h3>
        <h3 class="underline short">Проекты</h3>
        <a href="/proekty/" class="btn btn-default btn-xs wc"><i class="icon icon-bars"></i><span>Все проекты</span></a>
        <div class="row" style="margin-top: -5px;">
          <div class="flexslider unstyled row" data-plugin-options='{"animation": "slide", "directionNav": true, "controlNav" :false, "animationLoop": true, "slideshow": false, "counts": [3, 2, 1]}'>
            <ul class="slides items">
              {% for project in projects_list %}
              <li class="col-md-4 col-sm-6 item">
                <a href="{{project.get_absolute_url}}">
                  {% if project.image %}
                  <div class="image">
                    <img src="{{project.image.url}}" alt="{{project.menu_name}}" title="{{project.title}}" class="img-responsive" />
                  </div>
                  {% endif %}
                  <div class="info">
                    <div class="title">
                      <span>{{project.header_h1}}</span>
                    </div>
                  </div>
                </a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
      <hr>
      <div class="partners front">
        <h3>Наши партнеры</h3>
        <h3 class="short">Партнеры</h3>
        
        <div class="flexslider unstyled row" data-plugin-options='{"animation": "slide", "directionNav": true, "controlNav" :true, "animationLoop": true, "slideshow": false, "counts": [5, 3, 1]}'>
          <ul class="slides items">
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/hyundai.png' %}" alt="HYUNDAI" title="HYUNDAI" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/arena.png' %}" alt="АРЕНА" title="АРЕНА" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/beeline.png' %}" alt="БИЛАЙН" title="БИЛАЙН" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/gazprom.png' %}" alt="Газпром" title="Газпром" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/gdsk.png' %}" alt="ГДСК" title="ГДСК" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/gm.png' %}" alt="ГМ" title="ГМ" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/domina.png' %}" alt="ДОМИНА" title="ДОМИНА" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/kapitoliy.png' %}" alt="КАПИТОЛИЙ" title="КАПИТОЛИЙ" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/kir_zav.png' %}" alt="Кировский завод" title="Кировский завод" /></a>
            </li>
            <li class="col-md-2 col-sm-4 item">
              <a ><img class="img-responsive" src="{% static '/img/partners/kuz_plaza.png' %}" alt="Кунцево-плаза" title="Кунцево-плаза" /></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container maxwidth-theme">
    <div class="descr_text">
      {% autoescape off %}{{main_page.content_down}}{% endautoescape %}
    </div>
  </div>
</div>


</div>
</div>
</div>
	<footer id="footer">
			<div class="container maxwidth-theme">
				<div class="row">
          {% autoescape off %}{{footer_element.content}}{% endautoescape %}
        </div>
			</div>
	</footer>
{% endblock content%}